apiVersion: v1
kind: Service

metadata:
  name      : {{ template "name" . }}
  namespace : {{ .Values.namespace }}
  labels    :
    app     : {{ template "name" .       }}
    chart   : {{ template "chart.name" . }}
    release : {{ .Release.Name           }}
    heritage: {{ .Release.Service        }}

spec:
#  type: NodePort
  selector:
    name: {{ template "name" . }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}
  
