{{- if .Capabilities.APIVersions.Has "apps/v1" }}
apiVersion: apps/v1
{{- else }}
apiVersion: extensions/v1
{{- end }}
kind: Deployment

metadata:
  name      : {{ template "name" . }}
  namespace : {{ .Values.namespace }}
  labels:
    name    : {{ template "name" . }}
    type    : deployment
    chart   : {{ template "chart.name" . }}
    release : {{ .Release.Name }}
    heritage: {{ .Release.Service }}

spec:
  minReadySeconds: 10
  replicas: {{ default 1 .Values.replicaCount }}
  
  selector:
    matchLabels:
      name: {{ template "name" . }}
  
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: {{ .Values.rollingUpdate.maxUnavailable }}
      maxSurge      : {{ .Values.rollingUpdate.maxSurge }}
  
  template:
    metadata:
      name: {{ template "name" . }}
      labels:
        name    : {{ template "name" .       }}
        app     : {{ template "name" .       }}
        mService: {{ template "name" .       }}
        chart   : {{ template "chart.name" . }}
        release : {{ .Release.Name           }}
        heritage: {{ .Release.Service        }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.image.pullSecretName }}
      containers:
        - name: {{ template "name" . }}

          # Image
{{- if .Values.global.onPrem }}
          image:  {{ .Values.global.image.repository }}/{{ .Values.name }}:{{ .Values.image.tag }}
{{- else }}
          image:  {{ .Values.image.repository }}/{{ .Values.name }}:{{ .Values.image.tag }}
{{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          # Environment
          env:
          - name: BUILD_NUMBER
            value: {{ .Values.image.tag }}
          - name: NODE_ENV
            value: {{.Values.node_env}}
          - name: CONNECTIONS_HOST
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.env.configMapKeyRef.name }}
                key: ic-host
          - name: HOST_FILES_API
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.teams.configMapKeyRef.name }}
                key: host-files-api
          - name: SERVICE_HOSTNAME
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.teams.configMapKeyRef.name }}
                key: teams-share-service-endpoint
          
          # Ports
          ports:
          - containerPort: {{ .Values.service.internalPort }}
          
          #Readiness
          readinessProbe:
            httpGet:
              path: /teams-share-ui/picker
              httpHeaders:
                - name: Accept
                  value: '*/*'
              port: {{ .Values.service.internalPort }}
              scheme: {{ .Values.service.scheme }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}

          #Liveness
          livenessProbe:
            httpGet:
              path: /teams-share-ui/picker
              httpHeaders:
                - name: Accept
                  value: '*/*'
              port: {{ .Values.service.internalPort }}
              scheme: {{ .Values.service.scheme }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
          
          #Resources
          resources:
            limits:
              cpu: {{ .Values.resources.service.limits.cpu }}
              memory: {{ .Values.resources.service.limits.memory }}
            requests:
              cpu: {{ .Values.resources.service.requests.cpu }}
              memory: {{ .Values.resources.service.requests.memory }}

